version: '3.8'

services:
  traefik:
    image: traefik:v2.10
    ports:
      - "80:80"
      - "443:443"
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpChallenge.entryPoint=web"
      - "--certificatesresolvers.myresolver.acme.email=admin@example.com"
      - "--certificatesresolvers.myresolver.acme.storage=/etc/traefik/acme.json"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "traefik-data:/etc/traefik"
    deploy:
      placement:
        constraints:
          - node.role == manager
    restart: always
    labels:
      - "traefik.http.middlewares.auth.basicauth.users=admin:$$apr1$$randomhash"

  synchronre-front:
    image: synchronre-front-web:latest
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
        delay: 5s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.synchronre.rule=Host(`localhost.com`)"
      - "traefik.http.routers.synchronre.entrypoints=websecure"
      - "traefik.http.routers.synchronre.tls.certresolver=myresolver"
      - "traefik.http.services.synchronre.loadbalancer.server.port=80"
    networks:
      - web

networks:
  web:
    driver: overlay

volumes:
  traefik-data:
