version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: synchronre-front-web
    container_name: synchronre-front-web
    ports:
      - "80:80"
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
