version: '3.8'

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: always
    ports:
      - "80:80"    # HTTP
      - "8080:8080"  # Dashboard
    command:
      - "--api.insecure=true"  # Désactiver en prod
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  synchronre-front:
    image: synchronre-front-web:latest
    deploy:
      replicas: 3  # Nombre de réplicas du service Angular
      update_config:
        parallelism: 1  # Nombre de réplicas mis à jour simultanément
        delay: 10s  # Délai entre les mises à jour des réplicas
      restart_policy:
        condition: on-failure  # Redémarre si le conteneur échoue
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.synchronre.rule=Host(`localhost`)"
      - "traefik.http.services.synchronre.loadbalancer.server.port=8585"
    ports:
      - "8585:8585"  # Mapping du port
