version: '3.8'

services:
  traefik:
    image: traefik:v2.10
    ports:
      - "8585:80"      # HTTP (Traefik écoutant sur 8585, exposant sur 80)
      - "8085:8080"    # Dashboard (Traefik dashboard sur le port 8080, mais gardez-le exposé sur 8085 pour la gestion)
    command:
      - "--api.insecure=true"  # Désactiver en production
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "traefik-data:/etc/traefik"  # Pour persister la config de Traefik
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  synchronre-front:
    image: synchronre-front-web:latest
    deploy:
      replicas: 3  # Nombre de réplicas du service Angular
      update_config:
        parallelism: 1  # Nombre de réplicas mis à jour simultanément
        delay: 10s  # Délai entre les mises à jour des réplicas
      restart_policy:
        condition: on-failure  # Redémarre si le conteneur échoue
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.synchronre.rule=Host(`localhost.com`)"  # Nom de domaine personnalisé
      - "traefik.http.services.synchronre.loadbalancer.server.port=80"
    ports:
      - "8585:8585"  # Synchronre front expose sur le port 8585
    networks:
      - web

networks:
  web:
    driver: overlay  # Assure une communication réseau entre les conteneurs dans Swarm

volumes:
  traefik-data:  # Volume pour persister la configuration de Traefik
